sudo: false
language: php
php:
  - 7.2

before_script:
  - npm install -g grunt-cli
  - npm install
  - phpenv config-rm xdebug.ini
  - phpenv rehash

script:
  - npm test
  - composer self-update
  - composer install --prefer-dist
  - phpunit -c vendor/yireo/magento2-googletagmanager2/phpunit.xml vendor/yireo/magento2-googletagmanager2/Test/Unit
